// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OrangeMapshot","status":true,"description":"This plugin will save a picture of the entire map on a Mapshots folder when you press a key. <OrangeMapshot>","parameters":{"useMapName":"false","layerType":"0","drawAutoShadows":"false","keyCode":"44","imageType":"png","imageQuality":"100"}},
{"name":"SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}}
];
