// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_ActionIndicators","status":true,"description":"Display an icon when the player is able to interact with an event. View help for comment tag.","parameters":{"Y Offset":"0","Z Position":"5","Auto Hide":"true","Icon Opacity":"220"}}
];
